contests/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from .views import *

app_name = 'contests'
urlpatterns = [
    path('', ActiveProblemList.as_view(), name='home'),
    path('p/active/', ActiveProblemList.as_view(), name='active'),
    path('p/past/', PastProblemList.as_view(), name='past'),
    path('p/future/', FutureProblemList.as_view(), name='future'),
    path('p/<pid>/', problem_detail, name='problem'),
    path('p/<pid>/leaderboard/', problem_leader_view, name='prob_leader'),

    path('leaderboard/', user_leader_view, name='user_leader'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('contests.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from .views import *

app_name = 'users'
urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='login.htm'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('update/', UserUpdateView.as_view(), name='update'),
    path('<slug:pk>/', UserView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from .validators import *

class CustomUser(AbstractUser):
    """
    Custom user model. Flexible.
    """
    
    username = models.CharField(max_length=150, primary_key=True,
            validators=[forbid_username]) # forbids some inconvenient usernames
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    bio = models.TextField(default='')
    score = models.IntegerField(default=0) # ( ͡° ͜ʖ ͡°)

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.username})

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

# Custom Creation and Change forms because of the custom user model.

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'bio')

users/views.py
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from .forms import CustomUserCreationForm, CustomUserChangeForm
from contests.models import *

class SignUp(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'signup.htm'

class UserUpdateView(UpdateView):
    form_class = CustomUserChangeForm
    model = get_user_model()
    template_name = 'user_update.htm'
    context_object_name = 'user'

    def get_object(self, queryset=None):
        return self.request.user

class UserView(DetailView):
    model = get_user_model()
    template_name = 'user_profile.htm'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """
        Adds the following to the context:
        * is_logged_in
        * List of problems solved by the user: p_list
        * List of languages used: langs
        * Total character count across all solutions: total_count
        * Character count per solution submitted: avg_count

        """
        context = super().get_context_data(**kwargs)
        current_user = context['user']

        context['is_logged_in'] = (self.request.user == context['user'])

        # Gets the list of problems solved correctly
        p_list = Problem.objects.filter(solution__is_correct=True,
                solution__user=current_user)
        context['p_list'] = p_list

        # Logic to get list of programming languages used
        solns = Solution.objects.filter(user=current_user)
        langs = []
        for soln in solns:
            if soln.lang not in langs:
                langs.append(soln.lang)

        context['langs'] = langs

        # Logic for total and average character count
        if not solns:
            return context

        total_count = 0
        for soln in solns:
            total_count += soln.char_count

        avg_count = total_count // len(solns)
        context['total_count'] = total_count
        context['avg_count'] = avg_count

        return context

templates/base.htm
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/awsm.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">

    <title>
      {% block title %}{% endblock %} | NISER CodeGolf
    </title>
  </head>

  <body>
    <header>
      <h1>NISER CodeGolf</h1>
      {% if request.user.is_authenticated %}
      <p>
        Hello, {{request.user.username}}! Is your code short enough?
        <a href="{% url 'users:profile' request.user.username %}">Profile.</a>
      </p>
      {% else %}
      <p>Keep the number of strokes as low as possible to win.</p>
      {% endif %}

      <nav>
        <ul>
          <li>
            <a href="{% url 'contests:home' %}">Home</a>
          </li>

          <li>
            <a href="{% url 'contests:user_leader' %}">Leaderboard</a>
          </li>

          {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'users:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'users:login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'users:signup' %}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      {% if messages %}
      <ul class="messages">

        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
          {{ message }}
        </li>

        {% endfor %}
      </ul>

      {% endif %}

      {% block content %}
      {% endblock %}
    </main>

    <footer>
      NISER Coding Club
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js"></script>
    <script src="{% static 'scripts/main.js' %}"></script>
  </body>
</html>

templates/index.htm
{% extends 'base.htm' %}

{% block title %}
Home
{% endblock %}

{% block content %}

<h2>Problems</h2>

{% if p_list %}
<p>Here is the list of problems open for the competition now. Follow the links
for a full description, and to submit your code.</p>
<ol>

  {% for p in p_list %}
  <li>
    <a href="{% url 'contests:problem' p.id %}">{{ p.title }}</a>
  </li>

  {% endfor %}
</ol>

{% else %}
<p>There are no problems open in the competition now. Check back later!</p>

{% endif %}

{% endblock %}

templates/login.htm
{% extends 'base.htm' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<h2>Login</h2>
{% if user.is_authenticated %}
<p>You are already logged in. Go to the <a href="{% url 'contests:home' %}">main page</a> for fresh problems.</p>

{% else %}
<p>Login to your account to submit your code.</p>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

{% endif %}

{% endblock %}

templates/prob.htm
{% extends 'base.htm' %}

{% block title %}
{{ p.title }}
{% endblock %}

{% block content %}
<h2>{{ p.title }}</h2>

<p class="markdown">{{ p.text }}</p>

<div>
  {% if user.is_authenticated %}
  {% if s_form %}
  <form enctype="multipart/form-data" method="post">
    <legend>Submit Your Code Here</legend>
    {% csrf_token %}
    {{ s_form.as_p }}
    <button type="submit">Submit</button>
  </form>

  {% elif repeat_submission %}
  <p><em>You have already submitted a solution to this problem once. If it is
    not on the leaderboard, one of our moderators may not have verified it to
    be working yet.</em></p> 

  {% elif p.is_past %}
  <p><em>The competition for this problem is already over. Go to the 
    <a href="{% url 'contests:home' %}">main page</a> for fresh
    contests.</em></p>

  {% elif p.is_upcoming %}
  <p><em>You should not be seeing this.</em><p>

  {% endif %}

  {% else %}
  <p><a href="{% url 'users:login' %}">Log In</a> to submit a solution.</p>

  {% endif %}
</div>

<p><a href="{% url 'contests:prob_leader' p.id %}">Click here</a> for this
problem's leaderboard</p>

{% endblock %}

templates/prob_detail.htm
{% extends 'base.htm' %}

{% block title %}
{{ p.title }}
{% endblock %}

{% block content %}
<h3>{{ p.title }}</h3>

<ul class="prematter">
  {% if p.is_active %}
  <li>Problem open till {{ p.end }}</li>

  {% elif p.is_past %}
  <li>Problem closed {{ p.end }}</li>

  {% endif %}

  <li>
    {% if p.leader %}
    Problem leader: <a href="{% url 'users:profile' p.leader.username %}">{{p.leader}}</a>

    {% else %}
    There aren't any verified solutions for this problem yet.

    {% endif %}
  </li>

</ul>

<p class="markdown">
  <script>let prob_desc = '{{ p.text|escapejs }}';</script>
</p>

<div>
  {% if user.is_authenticated %}
  {% if s_form %}
  <form enctype="multipart/form-data" method="post">
    <legend>Submit Your Code Here</legend>
    {% csrf_token %}
    {{ s_form.as_p }}
    <button type="submit">Submit</button>
  </form>

  {% elif p.is_past %}
  <p><em>The competition for this problem is already over. Go to the 
    <a href="{% url 'contests:home' %}">main page</a> for fresh
    problems.</em></p>

  {% elif repeat_submission %}
  <p><em>You have already submitted a solution to this problem once. If it is
    not on the leaderboard, one of our moderators may not have verified it to
    be working yet.</em></p> 

  {% elif p.is_upcoming %}
  <p><em>You should not be seeing this.</em><p>

  {% endif %}

  {% else %}
  <p><a href="{% url 'users:login' %}">Log In</a> to submit a solution.</p>

  {% endif %}
</div>

<p><a href="{% url 'contests:prob_leader' p.id %}">Click here</a> for this
problem's leaderboard</p>

{% endblock %}

templates/prob_leader.htm
{% extends 'base.htm' %}

{% block title %}
Leaderboard for {{ prob.title }}
{% endblock %}

{% block content %}

<h2>Leaderboard for <em>{{ prob.title }}</em></h2>
<p><a href="{% url 'contests:problem' prob.id %}">Go back to the problem.</a></p> 

{% if solns %}
<table id="rankings">
  <tr>
    <th>Rank</th>
    <th>Username</th>
    <th>Full Name</th>
    <th>Character Count</th>
    <th>Language</th>
    {% if not prob.is_active %}<th>Solution</th>{% endif %}

  </tr>

  {% for soln in solns %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td><a href="{% url 'users:profile' soln.user.username %}">
        {{ soln.user }}</a></td>
    <td>{{ soln.user.first_name }} {{ soln.user.last_name }}</td>
    <td>{{ soln.char_count }}</td>
    <td>{{ soln.lang }}</td>
    {% if not prob.is_active %}<td>
      <a href="{{ soln.code.url }}">Code</a></td>{% endif %}

  </tr>
  {% endfor %}
</table>

{% else %}
<p>There are no verified solutions to this problem yet.</p>
{% endif %}

{% endblock %}

templates/prob_list.htm
{% extends 'base.htm' %}

{% block title %}
{{ state|title }} Problems
{% endblock %}

{% block content %}

<h2>Problems</h2>

<ul class="subnav">
  {% for s in all_states %}
  <li>
    {% if s == state %}
    <strong>{{ s|title }}</strong>
    {% else %}
    <a href="{% url 'contests:'|add:s %}">
      {{ s|title }}
    </a>
    {% endif %}
  </li>

  {% endfor %}
</ul>

{% if probs %}
<ul>
  {% for prob in probs %}
  <li>
    {% if state == 'future' %}
    <em>Undisclosed Problem #{{ forloop.counter }}</em>
    (Opens {{ prob.start }})

    {% else %}
    <a href="{% url 'contests:problem' prob.id %}">
    {{ prob.title }}</a> 

    {% if state == 'active' %}
    (Open till {{ prob.end }})
    {% elif state == 'past' %}
    (Closed {{ prob.end }})

    {% endif %}
    {% endif %}
  </li>

  {% endfor %}
</ul>

{% else %}
<p>No {{ state }} problems here.</p>

{% endif %}

{% endblock %}

templates/signup.htm
{% extends 'base.htm' %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<h2>Sign Up</h2>
{% if user.is_authenticated %}
<p>You are already logged in. Go to the <a href="{% url 'contests:home' %}">main page</a> for fresh problems.</p>

{% else %}
<p>Sign up for a new account to submit your code and compete in the
competition.</p>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>

{% endif %}
{% endblock %}

templates/user.htm
{% extends 'base.htm' %}

{% block title %}
{{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block content %}
<h3>{{ user.first_name }} {{ user.last_name }}</h3>

<p>{{ user.bio }}</p>

<ul>
  {% if p_list %}
  <li><strong>Characters per Solution: </strong>{{ avg_count }}</li>
  <li><strong>Total Character Count: </strong>{{ total_count }}</li>

  <li>
    <strong>Problems Solved:</strong>
    <ul class="comma">
      {% for p in p_list %}
      <li><em><a href="{% url 'contests:problem' p.id %}">
            {{ p.title }}</a></em></li> {% endfor %}
    </ul>
  </li>

  <li>
    <strong>Programming Languages Used:</strong>
    <ul class="comma">
      {% for l in langs %}
      <li>{{ l }}</li>
      {% endfor %}
    </ul>
    
    {% else %}
    <li>{{ user.first_name }} has not solved any problems yet.
    {% endif %}
  </li>
  
</ul>

{% endblock %}

templates/user_leader.htm
{% extends 'base.htm' %}

{% block title %}
Leaderboard
{% endblock %}

{% block content %}
<h2>Leaderboard</h2>

<p></p>

<table id="rankings">
  <tr>
    <th>Rank</th>
    <th>Username</th>
    <th>Full Name</th>
    <th>Score</th>

  </tr>

  {% for user in users %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td><a href="{% url 'users:profile' user.username %}">
        {{ user }}</a></td>
    <td>{{ user.first_name }} {{ user.last_name }}</td>
    <td>{{ user.score }}</td>

  </tr>
  {% endfor %}

</table>
{% endblock %}

templates/user_profile.htm
{% extends 'base.htm' %}

{% block title %}
{{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block content %}
<h3>{{ user.first_name }} {{ user.last_name }}</h3>

<p>
  {{ user.bio }}

  {% if is_logged_in %}
  <a href="{% url 'users:update' %}">Edit Profile</a>
  {% endif %}
</p>

<ul>
  {% if p_list %}
  <li><strong>Characters per Solution: </strong>{{ avg_count }}</li>
  <li><strong>Total Character Count: </strong>{{ total_count }}</li>

  <li>
    <strong>Problems Solved:</strong>
    <ul class="comma">
      {% for p in p_list %}
      <li><em><a href="{% url 'contests:problem' p.id %}">
            {{ p.title }}</a></em></li> {% endfor %}
    </ul>
  </li>

  <li>
    <strong>Programming Languages Used:</strong>
    <ul class="comma">
      {% for l in langs %}
      <li>{{ l }}</li>
      {% endfor %}
    </ul>
    
    {% else %}
    <li>{{ user.first_name }} has not solved any problems yet.
    {% endif %}
  </li>
  
</ul>

{% endblock %}

templates/user_update.htm
{% extends 'base.htm' %}

{% block title %}
{{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block content %}
<h3>{{ user.first_name }} {{ user.last_name }}</h3>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

{% endblock %}